### ISSUE TITLE
Can i use Partial view

### ISSUE THREAD

**Issue by Provson** [volosoft/jtable#152]
Hi,

My field is :
Commercial: {
                    title: 'Commercial',
                    width: '100%',
                    display: function (data) {
                        return '@Html.Partial("Create/PartialView/ComboBox/Commercial")';
                    }
                }

Can i use partial view? and if yes, how can i use it?

Thank

**Comment by gmillerkramer** [comment]
I've tried several times and I cannot figure out how to get the simplest of jTables to work in a Partial View.
I have an _Layout.cshtml that points to an index.cshtml and a partial _jTableTestPartial.cshtml.
If I put the div and "layout" script in the index.cshtml the empty table is displayed. If I move the div and script to the _jTableTestPartial.cshtml it won't display. The div is empty. I have tried loaded and empty, neither work! 

It's extremely maddening because I have to use MVC and this is causing a major blockage to my productivity.

Thank you,
Greg

**Comment by gmillerkramer** [comment]
I've tried several times and I cannot figure out how to get the simplest of jTables to work in a Partial View.
I have an _Layout.cshtml that points to an index.cshtml and a partial _jTableTestPartial.cshtml.
If I put the div and "layout" script in the index.cshtml the empty table is displayed. If I move the div and script to the _jTableTestPartial.cshtml it won't display. The div is empty. I have tried loaded and empty, neither work! 

It's extremely maddening because I have to use MVC and this is causing a major blockage to my productivity.

Thank you,
Greg

**Comment by peterboccia** [comment]
Do you call the partial view asynchronously? If yes, you need to call the initialization there.
If no, maybe this is a common problem because maybe you put the jQuery ready function in the partial, but, as jQuery and MVC suggest, all the script of plugin (such as jQuery and other plugin) are loaded at the end of the body.
You need to create a function and then call it in the ready of the Index file, or you can put the scripts bundles in the head of the DOM.
Let us know if you resolve it.

**Comment by gmillerkramer** [comment]
I'm not sure if I'm calling it asynchronously. I don't think so. 
Basically, I a Views/_ViewStart.cshtml  Views/Home/Index.cshtml  Views/Shared/_Layout.cshtml   Views/Shared/_jTableDispPartial.cshtml. 

If the jTable div and script are in the Index.cshtml (like the code here. http://jtable.org/ApiReference ) it works fine. 

The minute I move the div and script into the partial view _jTableDispPartial.cshtml it fails. 

In the index.cshtml I'm calling @Html.Partial("_jTableDispPartial") to bring the table in. This is what fails. 

I've tried putting the jtable js and css in the partial view and that doesn't work. All the js and css loads are in the _Layout.cshtml with @Styles.Render and @Scripts.Render.

This is very frustrating. We do NOT want to fall back to Infragistics, but if I can't get this working we may have to.

Thank you for your assistance.

Greg

**Comment by gmillerkramer** [comment]
Anyone? At this point I don't see us using jTable because we can't figure out a way to get the jTable to work within a partial view.

Does anyone have some help to make it work?

Thank you.
Greg
