### ISSUE TITLE
width not working

### ISSUE THREAD

**Issue by pwinston** [volosoft/jtable#1649]
I'm using latest and width just seems to do nothing in my case.

I have tried %:

```
outdir: {
    title: 'Directory',
    width: '10%',
},
```

and an integer

```
outdir: {
    title: 'Directory',
    width: 25,
},
```

Neither seems to do anything.

My table is the only thing on the page just like the examples:

  <body>
    <div id="DatasetTable"></div>
    <script type="text/javascript">

```
    $(document).ready(function () {

        $('#DatasetTable').jtable({
```

Any ideas?

**Comment by MirkoGitHub** [comment]
Hi, don't know why, but if you set tableId, the width attribute seems work correctly.

**Comment by kenirwin** [comment]
Have you checked to see if the width was specified in an html style attribute? I was having trouble resizing my table and then noticed this in my html:
`<div id="TableContainer" style="width: 600px;"></div>`
as copied from the samples. My stylesheet didn't work because it was over-ridden by the html attribute.

**Comment by pwinston** [comment]
Not getting back to his so closing.
