### ISSUE TITLE
add a column select button as alternative to the context menu

### ISSUE THREAD

**Issue by goerob** [volosoft/jtable#2260]
Hi,

I would like to add a "Column selection" button next to the "Add new record" button. Many of my users do not know that they can change the visible columns because using the context menu is not common for most web applications.

Is there a easy way to do this?

**Comment by misterparsons** [comment]
Hi,

The Column Visibility panel is created in response to a contextmenu event bound to the table thead. You can make it appear programmatically by triggering the contextmenu manually.

Here is a snippet that you can adapt to your needs,
```
	toolbar:  {
		items: [{
			text: 'Select Columns',
			click: function () {
				var th = $("#yourDivName thead th.jtable-column-header").last();
				var p = th.position();
				var e = jQuery.Event( "contextmenu",{ pageX: p.left + 50, pageY:p.top+50} );
				th.trigger(e);	
			}
		}]
	},
```
The toolbar functions are best described as callbacks rather than events, so there is no DOM context ie $(this) for them, so you need to code the id of the container.
What I do is find the last named column in the jtable.
I get the position in order to create a position for the new contextmenu event.
Finally trigger the event.

Good Luck
Malcolm

**Comment by goerob** [comment]
Hi Malcolm,

thank you very much. Your solution works like a charm.
Much cleaner than the approaches I tried before.

thx
Robert
